site_name: "red-dwarf"
docs_dir: .

exclude_docs: |
  /tests

theme:
  name: "readthedocs"

nav:
  - Home: README.md
  - "API Reference": docs/api_reference.md

plugins:
- search
- same-dir
- mkdocstrings
