site_name: "red-dwarf"
docs_dir: .

repo_url: https://github.com/polis-community/red-dwarf/
edit_uri: edit/main/

exclude_docs: |
  /tests

theme:
  name: "readthedocs"

nav:
  - Home: README.md
  - "API Reference": docs/api_reference.md

plugins:
- search
- same-dir
- mkdocstrings
