[project]
name = "reddwarf"
version = "0.1.0"
description = "A dimensional reduction library for stellarpunk democracy into the long haul"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "polars>=1.19.0",
]

[tool.setuptools.packages.find]
include = ["reddwarf*"]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.4",
]
