[project]
name = "reddwarf"
version = "0.1.0"
description = "A dimensional reduction library for stellarpunk democracy into the long haul"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fake-useragent>=2.0.3",
    "matplotlib>=3.10.0",
    "pandas>=2.2.2",
    "polars>=1.19.0",
    "requests-cache>=1.2.1",
    "requests>=2.32.3",
    "scikit-learn>=1.6.0",
    "requests-ratelimiter>=0.7.0",
]

[tool.setuptools.packages.find]
include = ["reddwarf*"]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.4",
]
