on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Install dependencies
        run: make install-dev

      - name: Test with pytest
        run: make test
